/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <mpsl.h>
#include "mpsl_log_config.h"
#include "mpsl_log_msg.h"
#if defined(CONFIG_BT_CTLR_SDC_LOG)
#include "sdc_log_msg.h"
/* Both tables are generated by the same collector, so their rows are layout-identical. */
BUILD_ASSERT(sizeof(sdc_log_msgs[0]) == sizeof(struct mpsl_log_msg_entry));
#endif

LOG_MODULE_REGISTER(mpsl_log, CONFIG_MPSL_LOG_PRINT_LEVEL);

#define MPSL_LOG_FIFO_SIZE     CONFIG_MPSL_LOG_FIFO_SIZE
#define MPSL_LOG_MAX_ARGS      3U /* must match the dispatcher in mpsl_log_handlers.h */
#define MPSL_LOG_LINE_BUF_SIZE 128U /* max formatted line length; format strings are build-time bounded */

/* The dispatcher packs the library id into byte 2 and the message id into the low 16 bits. */
#define MPSL_LOG_LIB_ID_MPSL   0U
#define MPSL_LOG_LIB_ID_SDC    1U
#define MPSL_LOG_LIB_ID(id)    (((id) >> 16) & 0xFFU)
#define MPSL_LOG_MSG_ID(id)    ((uint16_t)((id) & 0xFFFFU))

/* Unused argv slots are zero; the format string reads only as many as it needs. */
struct mpsl_log_entry {
	uint32_t id;
	uint32_t argv[MPSL_LOG_MAX_ARGS];
};

K_MSGQ_DEFINE(mpsl_log_msgq, sizeof(struct mpsl_log_entry), MPSL_LOG_FIFO_SIZE, 4);

static int mpsl_log_id_cmp(const void *key, const void *elem)
{
	uint16_t id = *(const uint16_t *)key;
	const struct mpsl_log_msg_entry *entry = elem;

	if (id < entry->id) {
		return -1;
	}
	if (id > entry->id) {
		return 1;
	}
	return 0;
}

/* Resolve a runtime id to its build-time message table entry, or NULL if the id
 * belongs to an unknown library or was gated out at the configured log level. */
static const struct mpsl_log_msg_entry *mpsl_log_msg_lookup(uint32_t id)
{
	uint16_t msg_id = MPSL_LOG_MSG_ID(id);

	switch (MPSL_LOG_LIB_ID(id)) {
	case MPSL_LOG_LIB_ID_MPSL:
		/* The last table row is the 0xffff sentinel, excluded from the search. */
		return bsearch(&msg_id, mpsl_log_msgs, ARRAY_SIZE(mpsl_log_msgs) - 1,
			       sizeof(mpsl_log_msgs[0]), mpsl_log_id_cmp);
#if defined(CONFIG_BT_CTLR_SDC_LOG)
	case MPSL_LOG_LIB_ID_SDC:
		return (const struct mpsl_log_msg_entry *)
			bsearch(&msg_id, sdc_log_msgs, ARRAY_SIZE(sdc_log_msgs) - 1,
				sizeof(sdc_log_msgs[0]), mpsl_log_id_cmp);
#endif
	default:
		return NULL;
	}
}

static void mpsl_log_print(const struct mpsl_log_entry *entry)
{
	const struct mpsl_log_msg_entry *msg = mpsl_log_msg_lookup(entry->id);
	char line[MPSL_LOG_LINE_BUF_SIZE];

	if (msg == NULL) {
		return;
	}

	/* fmt is a trusted, build-time-generated string. The log-collection script
	 * rejects %s/%n and non-word specifiers so this stays memory-safe. Unused
	 * argument slots are zero and ignored by the format string.
	 */
	(void)snprintf(line, sizeof(line), msg->fmt,
		       entry->argv[0], entry->argv[1], entry->argv[2]);

	switch (msg->level) {
	case LOG_LEVEL_ERR:
		LOG_ERR("%s", line);
		break;
	default:
		LOG_INF("%s", line);
		break;
	}
}

static void mpsl_log_thread_fn(void *p1, void *p2, void *p3)
{
	struct mpsl_log_entry entry;

	ARG_UNUSED(p1);
	ARG_UNUSED(p2);
	ARG_UNUSED(p3);

	while (true) {
		if (k_msgq_get(&mpsl_log_msgq, &entry, K_FOREVER) == 0) {
			mpsl_log_print(&entry);
		}
	}
}

/* Registered via mpsl_log_handlers_set(); run in the MPSL/SDC calling context, so they
 * must only enqueue and defer printing to the log thread. */
static void mpsl_log_enqueue0(uint32_t id)
{
	struct mpsl_log_entry entry = { .id = id };

	(void)k_msgq_put(&mpsl_log_msgq, &entry, K_NO_WAIT);
}

static void mpsl_log_enqueue1(uint32_t id, uint32_t a0)
{
	struct mpsl_log_entry entry = { .id = id, .argv = { a0 } };

	(void)k_msgq_put(&mpsl_log_msgq, &entry, K_NO_WAIT);
}

static void mpsl_log_enqueue2(uint32_t id, uint32_t a0, uint32_t a1)
{
	struct mpsl_log_entry entry = { .id = id, .argv = { a0, a1 } };

	(void)k_msgq_put(&mpsl_log_msgq, &entry, K_NO_WAIT);
}

static void mpsl_log_enqueue3(uint32_t id, uint32_t a0, uint32_t a1, uint32_t a2)
{
	struct mpsl_log_entry entry = { .id = id, .argv = { a0, a1, a2 } };

	(void)k_msgq_put(&mpsl_log_msgq, &entry, K_NO_WAIT);
}

static const mpsl_log_handlers_t mpsl_log_handlers = {
	.log0 = mpsl_log_enqueue0,
	.log1 = mpsl_log_enqueue1,
	.log2 = mpsl_log_enqueue2,
	.log3 = mpsl_log_enqueue3,
};

/* Static drain thread; blocks on the FIFO until messages arrive. */
K_THREAD_DEFINE(mpsl_log_thread, CONFIG_MPSL_LOG_THREAD_STACK_SIZE,
		mpsl_log_thread_fn, NULL, NULL, NULL,
		K_PRIO_PREEMPT(CONFIG_SYSTEM_WORKQUEUE_PRIORITY), 0, 0);

/* Registering the handler is only a pointer write, so do it at the earliest init level.
 * This is before any POST_KERNEL controller init, so the first mpsl_init()/sdc_init() log
 * is captured without depending on any specific init-priority relationship. */
static int mpsl_log_register(void)
{
	return mpsl_log_handlers_set(&mpsl_log_handlers);
}

SYS_INIT(mpsl_log_register, PRE_KERNEL_1, 0);
